"""Remove email from patients

Revision ID: remove_email_from_patients
Revises: 12b18e03f589
Create Date: 2025-10-26 18:12:30.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'remove_email_from_patients'
down_revision: Union[str, Sequence[str], None] = '12b18e03f589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###